### PR TITLE
Update to version 7.0.0 from tar sources

### PR DESCRIPTION
**Pull request by sawenzel**
- http://releases.llvm.org/7.0.0/cfe-7.0.0.src.tar.xz
  - http://releases.llvm.org/7.0.0/llvm-7.0.0.src.tar.xz
  - http://releases.llvm.org/7.0.0/clang-tools-extra-7.0.0.src.tar.xz

### CODE REVIEW

**Comment by sawenzel** [comment]
This is required to make the codechecker work again after the move to C++17.

**Comment by dberzano** [comment]
Is it ready to be merged?

**Comment by dberzano** [comment]
(Also, how should we name the tag?)

**Comment by sawenzel** [comment]
Sorry. just realized that the clang.sh recipe takes from master. So actually no tag required.

**Comment by dberzano** [comment]
@sawenzel we need to change the recipe then, as per policy, and tag.

**Comment by dberzano** [comment]
There is a reason for that: aliBuild does not automatically, on local computers, check if an upstream branch has changed for performance reasons (it does that on the C.I. and automatic builds of course, and it can be forcefully enabled with `--fetch-repos` or `-u`).

So if we don't create a tag, local users may be affected unless they add that option.

As per policy, the decision was to always use tags everywhere (you may find that O2 specifies `dev`, but it's meant to be used as a development package, so it does not matter).

**Pull request merged**
